# Generated by Django 2.1.3 on 2019-07-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr_app', '0002_auto_20190630_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_price', models.IntegerField()),
                ('business_suite_price', models.IntegerField()),
                ('presedential_suite_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('hotel_name', 'city_name')},
        ),
        migrations.AddField(
            model_name='pricing',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr_app.Hotel'),
        ),
    ]
