# Generated by Django 2.1.3 on 2019-07-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr_app', '0003_auto_20190703_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='id',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cr_app.Hotel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
